name = "PHILLIPO"
uuid = "446a1a6f-4221-4af0-a98d-e0fa6c9694c7"
authors = ["Lucas Bublitz <lucasbublitz0@gmail.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
